# ================================================
# GNSS 配置文件示例
# ================================================

GPS=1
BD2=1
GLO=0

navFile=./data/gps_nav.24n
obsFile=./data/obs.24o

noiseGPSCode=0.3
noiseGPSPhase=0.001
noiseBDSCode=0.35
noiseBDSPhase=0.0015
noiseGLO=0.4

maxIter=20
threshold=0.001
